[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.28"
egui-miniquad = "0.15"
egui_plot = "0.28"
fern = "0.6"
humantime = "2.1"
log = "0.4"
miniquad = "0.4"
nalgebra = "0.33"
parking_lot = "0.12"
rand = "0.8"
rand_distr = "0.4"
