[project]
name = "sfm"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "hloc",
]

[tool.uv]
dev-dependencies = [
    "mypy>=1.12.0",
    "pyright>=1.1.384",
    "ruff>=0.6.9",
]

[tool.uv.sources]
hloc = { git = "https://github.com/cvg/Hierarchical-Localization" }
